name: elostupi
description: "GestÃ£o ElosTupi."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.6.0
  get: ^4.7.3
  get_storage: ^2.1.1
  wakelock_plus: ^1.4.0
  intl: ^0.20.2
  bluetooth_print_plus: ^2.4.6
  persistent_bottom_nav_bar_v2: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


